version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017"
#  zookeeper:
#    image: wurstmeister/zookeeper:latest
#    ports:
#      - "2181:2181"
  zkbrowser:
    depends_on:
      - "kafka_zookeeper"
    image: mijalko/zkbrowser:latest
    ports:
      - "4550:4550"
  kafka_zookeeper:
    image: spotify/kafka
    environment:
      ADVERTISED_HOST: kafka_zookeeper
      ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: "true"
    ports:
      - "9092"
      - "2181"
#  kafka:
#    depends_on:
#      - "zookeeper"
#    image: "wurstmeister/kafka:0.8.2.1"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "as-gps,as-raw-gps,as-segments"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - "9092"
  redis:
    image: "redis"
    ports:
      - "6379"
  mysql:
    image: "mysql"
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: as-management
  as-device-manager:
    depends_on:
      - kafka_zookeeper
    image: "localhost:5000/tikal/as-device-manager:latest"
    ports:
      - "4080"
  as-geocoder-facade:
    depends_on:
      - redis
    image: "localhost:5000/tikal/as-geocoder-facade:latest"
    ports:
      - "7080"
  as-gps-firehose:
    depends_on:
      - as-device-manager
    image: "localhost:5000/tikal/as-gps-firehose:latest"
    ports:
      - "6080"
  as-gps-service:
    depends_on:
      - mongo
      - kafka_zookeeper
      - as-management
    image: "localhost:5000/tikal/as-gps-service:latest"
    ports:
      - "8080"
  as-management:
    depends_on:
      - mysql
    image: "localhost:5000/tikal/as-management:latest"
    ports:
      - "3080"
  as-notifications:
    depends_on:
      - as-management
      - kafka_zookeeper
    image: "localhost:5000/tikal/as-notifications:latest"
    ports:
      - "5080"
  as-segments-service:
    depends_on:
      - mongo
      - kafka_zookeeper
    image: "localhost:5000/tikal/as-segments-service:latest"
    ports:
      - "8888"
  gps-tracker-ui:
    depends_on:
      - as-management
      - as-gps-service
      - as-segments-service
    image: "localhost:5000/tikal/gps-tracker-ui:latest"
    ports:
      - "3000"
  as-analytics:
    depends_on:
      - redis
      - kafka_zookeeper
      - as-geocoder-facade
    hostname: as-analytics
    image: "localhost:5000/tikal/as-analytics:latest"
