version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017"
  as-zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
      - 2888
      - 3888
  as-kafka:
    depends_on:
      - "as-zookeeper"
    image: "wurstmeister/kafka:latest"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: as-kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: as-zookeeper:2181
      KAFKA_CREATE_TOPICS: "as-gps:1:1,as-raw-gps:1:1,as-segments:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
  zkbrowser:
    depends_on:
      - "as-zookeeper"
    image: mijalko/zkbrowser:latest
    ports:
      - "4550:4550"
#  kafka_zookeeper:
#    image: spotify/kafka
#    environment:
#      ADVERTISED_HOST: kafka_zookeeper
#      ADVERTISED_PORT: 9092
#      AUTO_CREATE_TOPICS: "true"
#    ports:
#      - "9092"
#      - "2181"
  as-redis:
    image: "redis"
    ports:
      - "6379"
  mysql:
    image: "mysql"
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: as-management
#  infra:
#    depends_on:
#      - redis
#      - mysql
#      - mongo
#      - zookeeper
#      - kafka
  as-device-manager:
    depends_on:
      - as-kafka
      - as-gps-firehose
    image: "docker-registry.tikalk.com:5000/tikal/as-device-manager:latest"
    ports:
      - "4080"
  as-geocoder-facade:
    depends_on:
      - as-redis
    image: "docker-registry.tikalk.com:5000/tikal/as-geocoder-facade:latest"
    ports:
      - "7080"
  as-gps-firehose:
    image: "docker-registry.tikalk.com:5000/tikal/as-gps-firehose:latest"
    ports:
      - "6080"
  as-gps-service:
    depends_on:
      - mongo
      - as-zookeeper
      - as-kafka
      - as-management
      - as-device-manager
    image: "docker-registry.tikalk.com:5000/tikal/as-gps-service:latest"
    ports:
      - "8080"
  as-management:
    depends_on:
      - mysql
    image: "docker-registry.tikalk.com:5000/tikal/as-management:latest"
    ports:
      - "3080"
  as-notifications:
    depends_on:
      - as-management
      - as-segments-service
      - as-zookeeper
      - as-kafka
    image: "docker-registry.tikalk.com:5000/tikal/as-notifications:latest"
    ports:
      - "5080"
  as-segments-service:
    depends_on:
      - mongo
      - as-zookeeper
      - as-kafka
    image: "docker-registry.tikalk.com:5000/tikal/as-segments-service:latest"
    ports:
      - "8888"
  gps-tracker-ui:
    depends_on:
      - as-management
      - as-gps-service
      - as-segments-service
    image: "docker-registry.tikalk.com:5000/tikal/gps-tracker-ui:latest"
    ports:
      - "3000:3000"
  as-analytics:
    depends_on:
      - as-redis
      - as-kafka
      - as-geocoder-facade
    hostname: as-analytics
    image: "docker-registry.tikalk.com:5000/tikal/as-analytics:latest"
